version: 2.1
jobs:
  yarn1:
    docker: 
      - image: cimg/node:14 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory

      - run: yarn global add node-gyp && yarn install
