version: 2.1
workflows:
  workflow1:
    jobs:
      - hello
      - yarn1

jobs:
  hello:
    docker: 
      - image: cimg/node:14 # the primary container, where your job's commands are run
    steps: 
      - checkout
      - run: echo "Hello World"
  yarn1:
    docker: 
      - image: cimg/node:14 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
        key: npm-v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn global add node-gyp && yarn install

      - save_cache: 
        key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
        paths: ./node_modules