version: 2.1

workflows: 
  std:
    jobs:
      - yarn
      - lint:
          requires:
            - yarn
      - test:
          requires:
            - yarn
      - e2e-test:
          requires:
            - yarn

jobs:
  yarn:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn global add node-gyp && yarn install

      - save_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  lint:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn lint
      - run: yarn format:check

  test:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test:ci

  e2e-test:
    docker:
      - image: cimg/node:14.10.1
        environment:
          DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psdb
          JWT_SECRET: ARMA, l'eau de combat
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test:e2e